# Generated by Django 4.2.1 on 2023-06-02 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_news_or_article', models.CharField(choices=[('Новости', 'Новости'), ('Статьи', 'Статьи')], max_length=20)),
                ('date_post', models.DateTimeField(auto_now_add=True)),
                ('article_title', models.CharField(max_length=100)),
                ('text_article', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('id_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Author.author')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Author.category')),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Author.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='id_category',
            field=models.ManyToManyField(through='Author.PostCategory', to='Author.category'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.TextField()),
                ('date_time_post', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(default=0)),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Author.post')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
